version: "3.9"
services:
  api-gateway:
    container_name: api-gateway
    build: api-gateway
    ports:
      - "8000:8000"
    networks:
      - product-network
  service-discovery:
    container_name: service-discovery
    build: service-discovery
    ports:
      - "8001:8001"
    networks:
      - product-network
  product-service:
    container_name: product-service
    build: product-service
    ports:
      - "8002:8002"
    networks:
      - product-network
  order-service:
    container_name: order-service
    build: order-service
    ports:
      - "8003:8003"
    networks:
      - product-network
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    networks:
      - product-network

networks:
  product-network:
    external: false
    name: product-network