version: "3.9"
services:
  api-gateway:
    image: api-gateway  	
    container_name: api-gateway
    build: api-gateway
    ports:
      - target: 8000
        published: 8000
        mode: host
    networks:
      - product-network
    depends_on:
      - db
      - keycloak

  service-discovery:
    container_name: service-discovery
    image: service-discovery  
    build: service-discovery
    ports:
      - target: 8001
        published: 8001
        mode: host
    networks:
      - product-network

  product-service:
    image: product-service
    container_name: product-service
    build: product-service
    networks:
      - product-network
    depends_on:
      - db

  order-service:
    image: order-service
    container_name: order-service
    build: order-service
    depends_on:
      - db
    networks:
      - product-network

  db:
    image: db
    container_name: db
    build: db
    restart: always
    ports:
      - target: 3306
        published: 3306
        mode: host
    networks:
      - product-network

  phpmyadmin:
    image: pma
    container_name: pma
    restart: always
    ports:
      - target: 80
        published: 8004
        mode: host
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MARIADB_ROOT_PASSWORD: admin
    networks:
      - product-network
      
  keycloak:
    image: keycloak
    container_name: keycloak
    ports:
      - target: 8080
        published: 8005
        mode: host
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mariadb
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=admin
      - DB_PASSWORD=admin
    depends_on:
      - db
    networks:
      - product-network

networks:
  product-network:
    external: false
    name: product-network
