spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mariadb://mariadb:3306/application
    username: admin
    password: admin

server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8001/eureka