spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mariadb://db:3306/products
    username: admin
    password: admin

  flyway:
    url: jdbc:mariadb://db:3306/products?currentSchema=app
    user: admin
    password: admin

server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8001/eureka